print('Welcome to the comparison operations')

print(2 == 2)
print('hello' == 'bye')
print('bye' == 'Bye')
print(3 == 3.0)
print(3 == '3')
print(3 != 4)
print(2 < 1)
print(3 <= 4)
print(4 >= 2)

print(1 < 2 < 3)
print((1 < 3) and (3 < 4))
print('hi' == 'hi' and 2.0 > 3)
print(1 == 3 or 2 < 3)
print(not 1 == 3)
print(not "hi" == 'hi')
